
export const photo = ([
        {id:1, order:0, title:'winter',image: require("./img/1.jpeg"), style: "red", tegs: 'game'},
        {id:2, order:2, title:'winter',image: require("./img/2.jpg"), style: "red", tegs: 'other'},
        {id:3, order:3, title:'winter',image: require("./img/3.jpg"), style: "red", tegs: 'game'},
        {id:4, order:4, title:'winter',image: require("./img/4.jpg"), style: "red", tegs: 'game'},
        {id:5, order:5, title:'winter',image: require("./img/5.jpg"), style: "red", tegs: 'other'},
        {id:6, order:6, title:'winter',image: require("./img/6.jpg"), style: "red", tegs: 'other'},
        {id:7, order:7, title:'winter',image: require("./img/7.jpg"), style: "red", tegs: 'monster'},
        {id:8, order:8, title:'winter',image: require("./img/8.jpg"), style: "red", tegs: 'game'},
        {id:9, order:9, title:'winter',image: require("./img/9.jpg"), style: "red", tegs: 'game'},
        {id:10, order:10, title:'winter',image: require("./img/10.jpg"), style: "red", tegs: 'monster'},
        {id:11, order:11, title:'winter',image: require("./img/11.jpg"), style: "red", tegs: 'other'},
        {id:12, order:12, title:'winter',image: require("./img/12.jpg"), style: "red", tegs: 'monster'},
        {id:13, order:13, title:'winter',image: require("./img/13.jpg"), style: "red", tegs: 'other'},
        {id:14, order:14, title:'winter',image: require("./img/14.jpg"), style: "red", tegs: 'game'},
        {id:15, order:15, title:'winter',image: require("./img/15.jpg"), style: "red", tegs: 'game'},
        {id:16, order:16, title:'winter',image: require("./img/16.jpg"), style: "red", tegs: 'game'},
        {id:17, order:17, title:'winter',image: require("./img/17.jpg"), style: "red", tegs: 'game'},
        {id:18, order:18, title:'winter',image: require("./img/18.jpg"), style: "red", tegs: 'other'},
        {id:19, order:19, title:'winter',image: require("./img/19.jpg"), style: "red", tegs: 'game'},
        {id:20, order:20, title:'winter',image: require("./img/20.jpg"), style: "red", tegs: 'other'},
        {id:21, order:21, title:'winter',image: require("./img/1.jpeg"), style: "red", tegs: 'game'},
        {id:22, order:22, title:'winter',image: require("./img/2.jpg"), style: "red", tegs: 'other'},
        {id:23, order:23, title:'winter',image: require("./img/3.jpg"), style: "red", tegs: 'game'},
        {id:24, order:24, title:'winter',image: require("./img/4.jpg"), style: "red", tegs: 'game'},
        {id:25, order:25, title:'winter',image: require("./img/5.jpg"), style: "red", tegs: 'other'},
        {id:26, order:26, title:'winter',image: require("./img/6.jpg"), style: "red", tegs: 'other'},
        {id:27, order:27, title:'winter',image: require("./img/7.jpg"), style: "red", tegs: 'monster'},
        {id:28, order:28, title:'winter',image: require("./img/8.jpg"), style: "red", tegs: 'game'},
        {id:29, order:29, title:'winter',image: require("./img/9.jpg"), style: "red", tegs: 'game'},
        {id:30, order:30, title:'winter',image: require("./img/10.jpg"), style: "red", tegs: 'monster'},
        {id:31, order:31, title:'winter',image: require("./img/11.jpg"), style: "red", tegs: 'other'},
        {id:32, order:32, title:'winter',image: require("./img/12.jpg"), style: "red", tegs: 'monster'},
        {id:33, order:33, title:'winter',image: require("./img/13.jpg"), style: "red", tegs: 'other'},
        {id:34, order:34, title:'winter',image: require("./img/14.jpg"), style: "red", tegs: 'game'},
        {id:35, order:35, title:'winter',image: require("./img/15.jpg"), style: "red", tegs: 'game'},
        {id:36, order:36, title:'winter',image: require("./img/16.jpg"), style: "red", tegs: 'game'},
        {id:37, order:37, title:'winter',image: require("./img/17.jpg"), style: "red", tegs: 'game'},
        {id:38, order:38, title:'winter',image: require("./img/18.jpg"), style: "red", tegs: 'other'},
        {id:39, order:39, title:'winter',image: require("./img/19.jpg"), style: "red", tegs: 'game'},
        {id:40, order:40, title:'winter',image: require("./img/20.jpg"), style: "red", tegs: 'other'}
    ])
    export const photoTwo= ([
        {id:1, order:0, title:'winter',image: require("./img/41.jpg"), style: "red", tegs: 'game'},
        {id:2, order:2, title:'winter',image: require("./img/42.jpg"), style: "red", tegs: 'other'},
        {id:3, order:3, title:'winter',image: require("./img/43.jpg"), style: "red", tegs: 'game'},
        {id:4, order:4, title:'winter',image: require("./img/44.jpg"), style: "red", tegs: 'game'},
        {id:5, order:5, title:'winter',image: require("./img/45.jpg"), style: "red", tegs: 'other'},
        {id:6, order:6, title:'winter',image: require("./img/46.jpg"), style: "red", tegs: 'other'},
        {id:7, order:7, title:'winter',image: require("./img/47.jpg"), style: "red", tegs: 'monster'},
        {id:8, order:8, title:'winter',image: require("./img/48.jpg"), style: "red", tegs: 'game'},
        {id:9, order:9, title:'winter',image: require("./img/49.jpg"), style: "red", tegs: 'game'},
        {id:10, order:10, title:'winter',image: require("./img/50.jpg"), style: "red", tegs: 'monster'},
        {id:11, order:11, title:'winter',image: require("./img/51.jpg"), style: "red", tegs: 'other'},
        {id:12, order:12, title:'winter',image: require("./img/52.jpg"), style: "red", tegs: 'monster'}
    ])